trigger:
- main  # Adjust the branch name if necessary

variables:
  containerRegistry: nodeapi06.azurecr.io  # Replace with your ACR name
  imageName: add-service  # The image name for your service

stages:
- stage: Build
  displayName: Build Docker Image and Push to ACR
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    pool: 'antony-selfhosted'
    steps:

    - task: UseNode@1  # Use Node.js version 16.x (adjust version as needed)
      inputs:
        version: '16.x'

    - script: |
        docker build -t $(containerRegistry)/$(imageName):$(Build.BuildId) .
        docker push $(containerRegistry)/$(imageName):$(Build.BuildId)
      displayName: 'Build and Push Docker Image'
      env:
        DOCKER_REGISTRY: $(containerRegistry)
        DOCKER_IMAGE_NAME: $(imageName)