trigger:
- main  # Adjust the branch name if necessary

variables:
  containerRegistry: nodeapi06.azurecr.io  # Replace with your ACR name
  imageName: add-service  # The image name for your service

stages:
- stage: Build
  displayName: Build Docker Image and Push to ACR
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    pool: 'antony-selfhosted'
    steps:

    - task: UseNode@1  # Use Node.js version 16.x (adjust version as needed)
      inputs:
        version: '16.x'

    - powershell:  |
        # Install Chocolatey (Package manager for Windows)
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
        Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

        # Install Docker using Chocolatey
        choco install docker-desktop -y
        
        # Wait for Docker Desktop to start (can take a while)
        Start-Sleep -Seconds 30

        # Verify Docker is installed
        docker --version

        docker build -t $(containerRegistry)/$(imageName):$(Build.BuildId) .
        docker push $(containerRegistry)/$(imageName):$(Build.BuildId)
      displayName: 'Build and Push Docker Image'
      env:
        DOCKER_REGISTRY: $(containerRegistry)
        DOCKER_IMAGE_NAME: $(imageName)